language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - composer run-script lint
  - composer run-script test

after_success:
  - travis_retry php vendor/bin/php-coveralls

cache:
  directories:
    - "$HOME/.composer/cache/files"

git:
  depth: 5
